#!/usr/bin/env bash
# new_dynamic_material_user.sh — scaffold a C++ AActor (.h/.cpp) that, on
# BeginPlay, creates a UMaterialInstanceDynamic from its mesh's material via
# CreateDynamicMaterialInstance, then animates a named scalar parameter every
# Tick. This is the canonical UE runtime "change a material parameter" idiom:
# you do NOT edit the base Material at runtime — you make a Dynamic Material
# Instance (MID) and set its parameters.
#
# This writes FILES ONLY. It does not compile anything (no Unreal Engine is
# installed in this environment, and none is required to scaffold). Drop the
# generated .h/.cpp into your module's Source/<Module>/ folder, add them to the
# build (UBT picks up new files when you regenerate project files / rebuild),
# place the Actor in a level, and assign a Static Mesh + a *parameterized*
# Material (one whose Base Color / Emissive etc. is driven by a named
# Scalar/Vector Parameter — a plain Constant cannot be changed at runtime).
#
# The MID concept and the Material/MaterialInstanceConstant/
# MaterialInstanceDynamic hierarchy are doc-sourced from the embedded UE 5.6/5.7
# pages (references/api/, see Instanced_Materials.md and Graphics_Programming_
# Overview.md). The exact C++ method names (CreateDynamicMaterialInstance,
# SetScalarParameterValue, SetVectorParameterValue) follow the standard UE C++
# API; the docs themselves show the Blueprint path. Not compile-tested here.
#
# Usage:
#   new_dynamic_material_user.sh <ClassName> [output_dir] [ModuleApiMacro]
#
#   <ClassName>       PascalCase, no leading 'A' (it is added). e.g. PulsingProp
#                     -> APulsingProp, files PulsingProp.h / PulsingProp.cpp.
#   [output_dir]      Directory to write into (default: current directory).
#   [ModuleApiMacro]  Module export macro for UCLASS, e.g. MYGAME_API
#                     (default: derived as <CLASSNAME>_API, a safe placeholder
#                     you should replace with your real module's *_API macro).
#
# Example:
#   ./new_dynamic_material_user.sh PulsingProp Source/MyGame MYGAME_API

set -euo pipefail

NAME="${1:-}"
OUT_DIR="${2:-.}"

if [[ -z "$NAME" ]]; then
  echo "usage: new_dynamic_material_user.sh <ClassName> [output_dir] [ModuleApiMacro]" >&2
  exit 2
fi

# UE class names are plain C++ identifiers; reject anything UBT/UHT would choke
# on (spaces, slashes, dots). Strip a leading 'A' so we do not produce 'AAFoo'.
if [[ ! "$NAME" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "new_dynamic_material_user.sh: '$NAME' must be a plain identifier (letters, digits, _; no spaces/slashes/dots)." >&2
  exit 2
fi
NAME="${NAME#A}"   # caller may pass PulsingProp or APulsingProp; normalize.

UPPER="$(printf '%s' "$NAME" | tr '[:lower:]' '[:upper:]')"
API_MACRO="${3:-${UPPER}_API}"

mkdir -p "$OUT_DIR"
H_FILE="$OUT_DIR/$NAME.h"
CPP_FILE="$OUT_DIR/$NAME.cpp"

if [[ -e "$H_FILE" || -e "$CPP_FILE" ]]; then
  echo "new_dynamic_material_user.sh: $H_FILE or $CPP_FILE already exists; refusing to overwrite." >&2
  exit 1
fi

cat > "$H_FILE" <<HEADER
// $NAME.h — AActor that animates a Dynamic Material Instance scalar parameter.
// Generated by new_dynamic_material_user.sh.
//
// Runtime material changes go through a UMaterialInstanceDynamic (MID), never
// the base UMaterial. CreateDynamicMaterialInstance clones the assigned material
// into a per-instance MID and assigns it back to the component; you then call
// SetScalarParameterValue / SetVectorParameterValue with the *named* parameter.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "$NAME.generated.h"

class UStaticMeshComponent;
class UMaterialInstanceDynamic;

UCLASS()
class ${API_MACRO} A$NAME : public AActor
{
    GENERATED_BODY()

public:
    A$NAME();

    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;

protected:
    // The mesh whose material we drive. Assign a Static Mesh in the editor and
    // give it a *parameterized* material (Scalar/Vector Parameter nodes — a
    // plain Constant cannot be edited at runtime).
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Material",
              meta = (AllowPrivateAccess = "true"))
    TObjectPtr<UStaticMeshComponent> MeshComponent;

    // The named Scalar Parameter to animate. Must match a parameter that exists
    // in the assigned material's graph, or the call is silently ignored.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Material")
    FName ScalarParameterName = TEXT("EmissiveStrength");

    // Animation range/speed for the scalar parameter.
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Material")
    float MinValue = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Material")
    float MaxValue = 5.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Material")
    float PulseSpeed = 2.0f;

private:
    // The runtime material instance we create in BeginPlay and tweak in Tick.
    UPROPERTY(Transient)
    TObjectPtr<UMaterialInstanceDynamic> DynamicMaterial;

    float ElapsedTime = 0.0f;
};
HEADER

cat > "$CPP_FILE" <<SOURCE
// $NAME.cpp — see $NAME.h for the MID rationale.
#include "$NAME.h"

#include "Components/StaticMeshComponent.h"
#include "Materials/MaterialInstanceDynamic.h"

A$NAME::A$NAME()
{
    PrimaryActorTick.bCanEverTick = true;

    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
    RootComponent = MeshComponent;
}

void A$NAME::BeginPlay()
{
    Super::BeginPlay();

    if (MeshComponent == nullptr)
    {
        return;
    }

    // Create a Dynamic Material Instance from the material on element index 0.
    // This clones the assigned material into a per-instance MID AND assigns it
    // back to the component, so anything we set on DynamicMaterial shows up on
    // this actor only — the base Material asset is untouched.
    DynamicMaterial = MeshComponent->CreateDynamicMaterialInstance(0);

    if (DynamicMaterial == nullptr)
    {
        // No material assigned on element 0, or it could not be instanced.
        UE_LOG(LogTemp, Warning,
               TEXT("%s: CreateDynamicMaterialInstance returned null; assign a material to the mesh."),
               *GetName());
    }
}

void A$NAME::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);

    if (DynamicMaterial == nullptr)
    {
        return;
    }

    ElapsedTime += DeltaSeconds;

    // PingPong-style 0..1 oscillation, mapped into [MinValue, MaxValue].
    const float Alpha = 0.5f + 0.5f * FMath::Sin(ElapsedTime * PulseSpeed);
    const float Value = FMath::Lerp(MinValue, MaxValue, Alpha);

    // Set the *named* scalar parameter. The name must match a Scalar Parameter
    // in the material graph; an unknown name is silently ignored.
    DynamicMaterial->SetScalarParameterValue(ScalarParameterName, Value);

    // Vector parameters work the same way, e.g. a tint color:
    //   DynamicMaterial->SetVectorParameterValue(TEXT("Tint"), FLinearColor::Red);
}
SOURCE

echo "wrote $H_FILE"
echo "wrote $CPP_FILE"
