#!/usr/bin/env bash
# new_audio_actor.sh — scaffold a C++ AActor with a UAudioComponent that plays a
# USoundBase on BeginPlay, plus a PlayOneShotAtLocation helper that calls
# UGameplayStatics::PlaySoundAtLocation with a USoundAttenuation asset.
#
# File-only: writes .h/.cpp into <ModulePath>. No engine needed; the generated
# code is doc-sourced from the embedded UE 5.6/5.7 docs and was NOT compile-tested
# here (no Unreal Engine installed). Wire the Sound / Attenuation assets in the
# editor, and make sure the owning module's .Build.cs has "Engine" (it does by
# default) in PublicDependencyModuleNames.
#
# Usage:
#   new_audio_actor.sh <ModulePath> <ActorName> [ModuleApiName]
#     <ModulePath>     dir to write into, e.g. Source/MyGame
#     <ActorName>      class base name WITHOUT the A prefix, e.g. AudioBeacon
#     [ModuleApiName]  the MODULENAME_API macro prefix (UPPERCASE). Defaults to
#                      the uppercased basename of <ModulePath>.
#
# Example:
#   scripts/new_audio_actor.sh Source/MyGame AudioBeacon MYGAME

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <ModulePath> <ActorName> [ModuleApiName]" >&2
  echo "  e.g. $0 Source/MyGame AudioBeacon MYGAME" >&2
  exit 2
fi

MODULE_PATH="$1"
NAME="$2"                              # base name, no A prefix (e.g. AudioBeacon)
MODULE_API="${3:-}"

# UE actor classes are prefixed with A in source (class AFoo). The user passes the
# base name WITHOUT it; the generated class is "A${NAME}". If they accidentally
# typed the A prefix twice (e.g. "AAudioBeacon"), strip ONE leading A so we don't
# emit AAFoo. (A plain name like "AudioBeacon" keeps its A — we only collapse a
# doubled prefix that looks like "A" + "AnotherCapital".)
if [[ "$NAME" =~ ^A[A-Z] ]]; then
  NAME="${NAME:1}"
fi

if [[ -z "$MODULE_API" ]]; then
  base="$(basename "$MODULE_PATH")"
  # uppercase, strip non-alnum -> MODULENAME_API convention
  MODULE_API="$(printf '%s' "$base" | tr '[:lower:]' '[:upper:]' | tr -cd 'A-Z0-9_')"
fi
API_MACRO="${MODULE_API}_API"

mkdir -p "$MODULE_PATH"
HDR="$MODULE_PATH/${NAME}.h"
SRC="$MODULE_PATH/${NAME}.cpp"

if [[ -e "$HDR" || -e "$SRC" ]]; then
  echo "refusing to overwrite existing ${NAME}.h/.cpp in $MODULE_PATH" >&2
  exit 1
fi

cat > "$HDR" <<EOF
// ${NAME}.h — generated by unreal-audio/new_audio_actor.sh
// An AActor with a UAudioComponent. Assign Sound (+ optional Attenuation) in the
// editor; it plays on BeginPlay. PlayOneShotAtLocation() fires a 3D one-shot.
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "${NAME}.generated.h"

class UAudioComponent;
class USoundBase;
class USoundAttenuation;

UCLASS()
class ${API_MACRO} A${NAME} : public AActor
{
    GENERATED_BODY()

public:
    A${NAME}();

    /** Looping/persistent sound played from the AudioComponent on BeginPlay. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Audio")
    TObjectPtr<USoundBase> Sound;

    /** Attenuation asset. NULL = 2D / flat (no spatialization). Set for 3D. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Audio")
    TObjectPtr<USoundAttenuation> Attenuation;

    /** A one-shot SFX (e.g. impact) for PlayOneShotAtLocation(). */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Audio")
    TObjectPtr<USoundBase> OneShotSound;

    /** If true, play Sound automatically on BeginPlay. */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Audio")
    bool bAutoPlayOnBeginPlay = true;

    /** Fire OneShotSound as a 3D one-shot at WorldLocation using Attenuation. */
    UFUNCTION(BlueprintCallable, Category = "Audio")
    void PlayOneShotAtLocation(const FVector& WorldLocation);

    /** Set a Float Input on the playing MetaSound (matched by exact name). */
    UFUNCTION(BlueprintCallable, Category = "Audio")
    void SetMetaSoundFloat(FName ParamName, float Value);

protected:
    virtual void BeginPlay() override;

    /** The controllable source. Persists so we can Play/Stop/set params. */
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Audio")
    TObjectPtr<UAudioComponent> AudioComponent;
};
EOF

cat > "$SRC" <<EOF
// ${NAME}.cpp — generated by unreal-audio/new_audio_actor.sh
#include "${NAME}.h"

#include "Components/AudioComponent.h"
#include "Kismet/GameplayStatics.h"
#include "Sound/SoundBase.h"
#include "Sound/SoundAttenuation.h"

A${NAME}::A${NAME}()
{
    PrimaryActorTick.bCanEverTick = false;

    // A UAudioComponent gives us a controllable source (Play/Stop/fade/params).
    AudioComponent = CreateDefaultSubobject<UAudioComponent>(TEXT("AudioComponent"));
    RootComponent = AudioComponent;

    // Don't auto-activate; we choose when to play in BeginPlay.
    AudioComponent->bAutoActivate = false;
}

void A${NAME}::BeginPlay()
{
    Super::BeginPlay();

    if (bAutoPlayOnBeginPlay && Sound && AudioComponent)
    {
        AudioComponent->SetSound(Sound);
        // NULL Attenuation = 2D. A valid asset (with spatialization enabled)
        // makes the sound positional / 3D.
        AudioComponent->AttenuationSettings = Attenuation;
        AudioComponent->Play();
    }
}

void A${NAME}::PlayOneShotAtLocation(const FVector& WorldLocation)
{
    if (!OneShotSound)
    {
        return;
    }

    // Fire-and-forget 3D one-shot. Passing Attenuation gives it falloff + panning;
    // pass nullptr and it plays flat (2D) everywhere.
    UGameplayStatics::PlaySoundAtLocation(
        this,
        OneShotSound,
        WorldLocation,
        /*VolumeMultiplier*/ 1.0f,
        /*PitchMultiplier*/  1.0f,
        /*StartTime*/        0.0f,
        Attenuation,
        /*ConcurrencySettings*/ nullptr,
        /*OwningActor*/ this);
}

void A${NAME}::SetMetaSoundFloat(FName ParamName, float Value)
{
    // Works when Sound is a MetaSound Source with a Float Input named ParamName.
    if (AudioComponent)
    {
        AudioComponent->SetFloatParameter(ParamName, Value);
    }
}
EOF

echo "wrote:"
echo "  $HDR"
echo "  $SRC"
echo "class: A${NAME}  (API macro: ${API_MACRO})"
echo "next: assign Sound/Attenuation/OneShotSound in the editor; ensure the module's"
echo "      .Build.cs lists \"Engine\" (default). Doc-sourced, not compile-tested."
