#!/usr/bin/env bash
# new_niagara_spawner.sh — scaffold a C++ AActor that spawns a UNiagaraSystem and
# drives one User float parameter from gameplay.
#
# Niagara assets (the System / Emitters / Modules) are authored in the editor —
# you CANNOT scaffold a .uasset from a shell. What this writes is the *C++
# control side*: an AActor that, at BeginPlay, spawns a Niagara System attached
# to itself via UNiagaraFunctionLibrary::SpawnSystemAttached, caches the
# returned UNiagaraComponent, and exposes a Blueprint-callable function that sets
# a "User." float parameter (the gameplay -> Niagara interface).
#
# You then: (1) point the actor's NiagaraSystem property at your authored .uasset
# in the editor, and (2) make sure that System has a matching User parameter
# (Parameters panel -> User namespace) of type float.
#
# Usage:
#   new_niagara_spawner.sh <ClassName> <ModuleName> [OutputDir]
#     <ClassName>   C++ class WITHOUT the A prefix (e.g. ImpactFX -> AImpactFX)
#     <ModuleName>  your game module name (the API macro: <MODULE>_API)
#     [OutputDir]   defaults to ./Source/<ModuleName>
#
# File-only: writes <ClassName>.h / <ClassName>.cpp and prints the .Build.cs
# dependencies you must add. Does NOT compile (no engine here).

set -euo pipefail

CLASS="${1:-}"
MODULE="${2:-}"
OUTDIR="${3:-}"

if [[ -z "$CLASS" || -z "$MODULE" ]]; then
  echo "usage: $(basename "$0") <ClassName> <ModuleName> [OutputDir]" >&2
  echo "  e.g. $(basename "$0") ImpactFX MyGame Source/MyGame" >&2
  exit 2
fi

# Strip a leading 'A' if the caller passed the UE-prefixed name.
CLASS="${CLASS#A}"
API_MACRO="$(printf '%s' "$MODULE" | tr '[:lower:]' '[:upper:]')_API"
OUTDIR="${OUTDIR:-Source/$MODULE}"

mkdir -p "$OUTDIR"
HEADER="$OUTDIR/$CLASS.h"
SOURCE="$OUTDIR/$CLASS.cpp"

cat > "$HEADER" <<EOF
// $CLASS.h — spawns a Niagara System and drives a User float parameter.
// Generated by new_niagara_spawner.sh (doc-sourced, not compile-tested).
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "$CLASS.generated.h"

class UNiagaraSystem;
class UNiagaraComponent;

UCLASS()
class ${API_MACRO} A$CLASS : public AActor
{
	GENERATED_BODY()

public:
	A$CLASS();

	/** The authored Niagara System asset to spawn. Set this in the editor/BP. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "FX")
	TObjectPtr<UNiagaraSystem> NiagaraSystem = nullptr;

	/** Name of the User-namespace float parameter on the System (e.g. "Intensity"). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "FX")
	FName IntensityParameterName = TEXT("Intensity");

	/** Drive the User float parameter from gameplay (e.g. ramp an effect). */
	UFUNCTION(BlueprintCallable, Category = "FX")
	void SetIntensity(float NewIntensity);

protected:
	virtual void BeginPlay() override;

private:
	/** The live spawned component — set User params through this. */
	UPROPERTY(Transient)
	TObjectPtr<UNiagaraComponent> SpawnedFX = nullptr;
};
EOF

cat > "$SOURCE" <<EOF
// $CLASS.cpp — Niagara spawn + User-parameter control.
// Snippets are doc-sourced from the embedded UE 5.6/5.7 Niagara docs +
// NiagaraFunctionLibrary.h / NiagaraComponent.h; NOT compile-tested (no engine).
#include "$CLASS.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraComponent.h"

A$CLASS::A$CLASS()
{
	PrimaryActorTick.bCanEverTick = false;
}

void A$CLASS::BeginPlay()
{
	Super::BeginPlay();

	if (NiagaraSystem == nullptr)
	{
		return;
	}

	// Spawn the System attached to this actor's root. The returned
	// UNiagaraComponent is your handle for setting User parameters at runtime.
	SpawnedFX = UNiagaraFunctionLibrary::SpawnSystemAttached(
		NiagaraSystem,
		GetRootComponent(),
		NAME_None,                       // attach socket (NAME_None = root)
		FVector::ZeroVector,             // relative location
		FRotator::ZeroRotator,           // relative rotation
		EAttachLocation::KeepRelativeOffset,
		/*bAutoDestroy=*/ true);

	// Push an initial value into the System's "User." float parameter.
	SetIntensity(1.0f);
}

void A$CLASS::SetIntensity(float NewIntensity)
{
	if (SpawnedFX != nullptr)
	{
		// Sets the "User.<IntensityParameterName>" float on the live instance.
		// The System MUST expose a matching User-namespace float parameter.
		SpawnedFX->SetVariableFloat(IntensityParameterName, NewIntensity);
	}
}
EOF

echo "wrote:"
echo "  $HEADER"
echo "  $SOURCE"
echo
echo "Next steps:"
echo "  1. Add Niagara deps to ${MODULE}.Build.cs PublicDependencyModuleNames:"
echo "       \"Niagara\""
echo "  2. In the editor, set this actor's NiagaraSystem to your authored .uasset."
echo "  3. On that System, add a User-namespace float parameter named"
echo "     '${CLASS}'-relevant (default IntensityParameterName = \"Intensity\")."
echo "  4. Regenerate project files + build via scripts/unreal.sh (needs an engine)."
