#!/usr/bin/env bash
# new_unity_project.sh — scaffold a Unity 6 (6000.x) C# project DIRECTORY layout
# without an Editor.
#
# Unity has no offline "create a full C# project" pathway: the .csproj/.sln are
# generated by the Editor's IDE-integration package the first time the project
# is opened (or via -batchmode -executeMethod). The Library/ cache is also
# editor-generated. What IS portable and hand-writable is the on-disk project
# skeleton Unity reads on open: Assets/, Packages/manifest.json, ProjectSettings/
# and the .meta files. This script writes exactly that skeleton plus a sample
# .asmdef, a sample C# script + its .meta, a Unity .gitignore, and a README.
#
# After running, OPEN the dir in Unity 6 once (or run unity.sh -batchmode
# -projectPath <dir> -quit) to generate Library/, the .csproj and the .sln.
#
# Usage:
#   new_unity_project.sh <project_dir> <ProjectName>
#
# Verified: writes files only; runs with no Unity Editor installed.
# Doc-sourced layout (Unity 6 manual: default-directories, SpecialFolders,
# upm-manifestPrj, assembly-definition-file-format, AssetMetadata).

set -euo pipefail

DIR="${1:?usage: new_unity_project.sh <dir> <ProjectName>}"
NAME="${2:?usage: new_unity_project.sh <dir> <ProjectName>}"

if [[ -e "$DIR" && -n "$(ls -A "$DIR" 2>/dev/null || true)" ]]; then
  echo "new_unity_project.sh: '$DIR' exists and is not empty; refusing to overwrite." >&2
  exit 2
fi

# Editor version this skeleton targets. Unity rewrites ProjectVersion.txt to the
# exact installed 6000.x patch on first open; this is just a sane default.
EDITOR_VER="${UNITY_EDITOR_VERSION:-6000.0.0f1}"

# Helper: write a minimal .meta file with a fixed-but-unique-ish GUID.
# A real GUID is 32 lowercase hex chars. The Editor regenerates/normalizes these
# on import; what matters is that a .meta EXISTS and travels with its asset.
guid() { printf '%032x' "$(( (RANDOM<<30) ^ (RANDOM<<15) ^ RANDOM ^ $$ ^ $(date +%N 2>/dev/null || echo 0) ))" | cut -c1-32; }

folder_meta() { # $1 = path to write <asset>.meta for a folder
  cat > "$1.meta" <<EOF
fileFormatVersion: 2
guid: $(guid)
folderAsset: yes
DefaultImporter:
  externalObjects: {}
  userData:
  assetBundleName:
  assetBundleVariant:
EOF
}

mkdir -p "$DIR"

# --- Top-level required dirs (Unity manual: default-directories) ---
mkdir -p "$DIR/Assets"
mkdir -p "$DIR/Packages"
mkdir -p "$DIR/ProjectSettings"

# --- Assets/ source layout. 'Editor' and 'Resources' are RESERVED folder names
#     (SpecialFolders): Editor scripts never ship in a Player build. ---
mkdir -p "$DIR/Assets/Scripts/$NAME"
mkdir -p "$DIR/Assets/Scenes"
mkdir -p "$DIR/Assets/Editor"
mkdir -p "$DIR/Assets/Art"
mkdir -p "$DIR/Assets/Audio"
for d in Scripts "Scripts/$NAME" Scenes Editor Art Audio; do
  folder_meta "$DIR/Assets/$d"
done

# --- Project manifest (Packages/manifest.json). Keys per upm-manifestPrj.
#     If this is empty/absent the Package Manager loads nothing, so we ship the
#     core packages a fresh Unity 6 project depends on. ---
cat > "$DIR/Packages/manifest.json" <<'EOF'
{
  "dependencies": {
    "com.unity.ide.rider": "3.0.31",
    "com.unity.ide.visualstudio": "2.0.22",
    "com.unity.test-framework": "1.4.5",
    "com.unity.ugui": "2.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0"
  },
  "enableLockFile": true,
  "resolutionStrategy": "lowest"
}
EOF

# --- ProjectSettings: only the two files needed to identify the project & its
#     Editor version. Unity generates the rest (Graphics, Input, Tags, …) on
#     first open. ProjectVersion.txt format is what the Hub/Editor writes. ---
cat > "$DIR/ProjectSettings/ProjectVersion.txt" <<EOF
m_EditorVersion: $EDITOR_VER
m_EditorVersionWithRevision: $EDITOR_VER (000000000000)
EOF

cat > "$DIR/ProjectSettings/ProjectSettings.asset" <<EOF
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!129 &1
PlayerSettings:
  m_ObjectHideFlags: 0
  productName: $NAME
  companyName: DefaultCompany
  bundleVersion: 0.1.0
EOF

# --- Assembly Definition for the game code (assembly-definition-file-format).
#     Splitting code into an asmdef means changing one script no longer
#     recompiles ALL scripts. name MUST be unique across the project. ---
cat > "$DIR/Assets/Scripts/$NAME/$NAME.asmdef" <<EOF
{
    "name": "$NAME",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
EOF
cat > "$DIR/Assets/Scripts/$NAME/$NAME.asmdef.meta" <<EOF
fileFormatVersion: 2
guid: $(guid)
AssemblyDefinitionImporter:
  externalObjects: {}
  userData:
  assetBundleName:
  assetBundleVariant:
EOF

# --- A sample MonoBehaviour. The CLASS NAME MUST equal the FILE NAME for Unity
#     to attach it to a GameObject from the Inspector. ---
cat > "$DIR/Assets/Scripts/$NAME/Hello.cs" <<'EOF'
using UnityEngine;

// The class name (Hello) MUST match the file name (Hello.cs), or Unity won't
// let you add this script as a component. MonoBehaviour is the base type for
// scripts attached to GameObjects.
public class Hello : MonoBehaviour
{
    // Called once before the first frame, after the object is enabled.
    private void Start()
    {
        Debug.Log("hello from Unity C#");
    }

    // Called every frame. Time.deltaTime is seconds since the last frame.
    private void Update()
    {
    }
}
EOF
cat > "$DIR/Assets/Scripts/$NAME/Hello.cs.meta" <<EOF
fileFormatVersion: 2
guid: $(guid)
MonoImporter:
  externalObjects: {}
  serializedVersion: 2
  defaultReferences: []
  executionOrder: 0
  icon: {instanceID: 0}
  userData:
  assetBundleName:
  assetBundleVariant:
EOF

# --- Unity .gitignore (copied from assets/unity.gitignore conceptually).
#     Library/ Temp/ UserSettings/ are regenerated/local — never commit.
#     The .csproj/.sln are generated by the IDE package on open. ---
cat > "$DIR/.gitignore" <<'EOF'
# Unity 6 — regenerated caches & local working dirs (NEVER commit)
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
/[Mm]emoryCaptures/

# IDE / .NET solution files (regenerated by the editor's IDE integration)
*.csproj
*.sln
*.user
.vs/
.idea/
.vscode/

# OS / build cruft
.DS_Store
*.tmp
*.unitypackage
sysinfo.txt

# DO commit: /Assets/  /Packages/  /ProjectSettings/  and every *.meta file.
EOF

cat > "$DIR/README.md" <<EOF
# $NAME (Unity 6 project)

Scaffolded by the \`unity-project-setup\` skill (directory skeleton only — no
Editor was used). To finish setup:

1. Open this folder in Unity 6 (6000.x) via the Hub once. Unity generates
   \`Library/\`, the \`$NAME.csproj\` and the \`.sln\`, and fills out
   \`ProjectSettings/\`.
   Headless equivalent:
       scripts/unity.sh -batchmode -nographics -quit -projectPath "$PWD/$DIR" -logFile -
2. Commit \`Assets/\`, \`Packages/\`, \`ProjectSettings/\` and **all .meta files**.
   Never commit \`Library/\`, \`Temp/\`, \`UserSettings/\`, or the .csproj/.sln.

Editor version pin: ProjectSettings/ProjectVersion.txt ($EDITOR_VER).
EOF

echo "Scaffolded Unity 6 project '$NAME' at $DIR"
echo "  Assets/ Packages/manifest.json ProjectSettings/ .gitignore + sample asmdef & script (with .meta)"
echo "Next: open in Unity 6 once (or 'scripts/unity.sh -batchmode -nographics -quit -projectPath \"$DIR\" -logFile -')"
echo "      to generate Library/, the .csproj and the .sln."
