#!/usr/bin/env bash
# new_project.sh — scaffold a buildable Godot 4.6 C# (.NET 8) project.
#
# Produces exactly the files Godot itself generates on first C# script attach,
# plus a nuget.config pointing at the SDK nupkgs bundled with the mono editor so
# `dotnet build` works offline. Verified end-to-end against Godot 4.6.3-mono.
#
# Usage:
#   new_project.sh <project_dir> <ProjectName> [renderer]
#     renderer: forward_plus (default) | mobile | gl_compatibility
#
# After running: `dotnet build <dir>/<ProjectName>.csproj` and
# `scripts/godot.sh --headless --path <dir> --import` both succeed.

set -euo pipefail

DIR="${1:?usage: new_project.sh <dir> <Name> [renderer]}"
NAME="${2:?usage: new_project.sh <dir> <Name> [renderer]}"
RENDERER="${3:-forward_plus}"

case "$RENDERER" in
  forward_plus) FEATURE="Forward Plus" ;;
  mobile)       FEATURE="Mobile" ;;
  gl_compatibility) FEATURE="GL Compatibility" ;;
  *) echo "renderer must be forward_plus|mobile|gl_compatibility" >&2; exit 2 ;;
esac

# Discover the SDK version + bundled nupkgs dir from the editor install so the
# generated files always match the binary in use (don't hardcode 4.6.3 here).
GODOT_BIN="${GODOT4:-/home/reza/apps/Godot_v4.6.3-stable_mono_linux_x86_64/Godot_v4.6.3-stable_mono_linux.x86_64}"
GS_DIR="$(dirname "$GODOT_BIN")/GodotSharp"
NUPKGS="$GS_DIR/Tools/nupkgs"
SDK_VER="$(ls "$NUPKGS"/Godot.NET.Sdk.*.nupkg 2>/dev/null | sed -E 's/.*Godot\.NET\.Sdk\.([0-9.]+)\.nupkg/\1/' | head -1)"
SDK_VER="${SDK_VER:-4.6.3}"

mkdir -p "$DIR"

cat > "$DIR/project.godot" <<EOF
; Engine configuration file.
; Generated by godot-project-setup skill. Safe to edit by hand.

config_version=5

[application]

config/name="$NAME"
config/features=PackedStringArray("4.6", "C#", "$FEATURE")

[dotnet]

project/assembly_name="$NAME"
EOF

cat > "$DIR/$NAME.csproj" <<EOF
<Project Sdk="Godot.NET.Sdk/$SDK_VER">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <RootNamespace>$NAME</RootNamespace>
  </PropertyGroup>
</Project>
EOF

# Offline NuGet source. The bundled feed is listed FIRST so it is preferred,
# but nuget.org is left available so external packages still restore online.
cat > "$DIR/nuget.config" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="GodotBundled" value="$NUPKGS" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
EOF

cat > "$DIR/.gitignore" <<'EOF'
# Godot 4+ — everything Godot regenerates
.godot/
# .NET build output
bin/
obj/
*.user
EOF

# Standard source layout most teams use. Empty dirs get a .gdignore so Godot
# does not try to import them as resources before they have content.
for d in scripts scenes assets/art assets/audio; do
  mkdir -p "$DIR/$d"
done

echo "Scaffolded $NAME at $DIR (SDK Godot.NET.Sdk/$SDK_VER, net8.0, $RENDERER)."
echo "Next: dotnet build \"$DIR/$NAME.csproj\"  &&  godot.sh --headless --path \"$DIR\" --import"
