#!/usr/bin/env bash
# new_urp_shader.sh — write a minimal, valid, SRP-Batcher-compatible URP unlit
# shader (.shader) with a single editable color property.
#
# This writes a FILE ONLY. It does not import or compile anything (no Unity
# Editor is required, and none is installed in this environment). Drop the
# resulting .shader anywhere under your project's Assets/ folder; Unity imports
# it on next focus/refresh, after which you create a Material from it
# (right-click the .shader -> Create -> Material, or assign it in the Material
# inspector's Shader dropdown under "Example/").
#
# The HLSL skeleton is taken from the Unity 6 URP docs (RenderPipeline tag
# "UniversalPipeline", the Core.hlsl include, TransformObjectToHClip) and the
# SRP Batcher rules (all material properties in a UnityPerMaterial CBUFFER).
# See references/materials_and_shaders.md for line-by-line grounding.
#
# Usage:
#   new_urp_shader.sh <ShaderName> [output_dir]
#
#   <ShaderName>  PascalCase asset name, e.g. MyUnlit. Becomes the file
#                 MyUnlit.shader and the menu path "Example/MyUnlit".
#   [output_dir]  Directory to write into (default: current directory).
#
# Example:
#   ./new_urp_shader.sh TintUnlit Assets/Shaders

set -euo pipefail

NAME="${1:-}"
OUT_DIR="${2:-.}"

if [[ -z "$NAME" ]]; then
  echo "usage: new_urp_shader.sh <ShaderName> [output_dir]" >&2
  exit 2
fi

# Reject anything that isn't a plain identifier — shader/menu names choke on
# spaces, slashes, and dots, and they would also break the C# property lookup.
if [[ ! "$NAME" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "new_urp_shader.sh: '$NAME' must be a plain identifier (letters, digits, _; no spaces/slashes/dots)." >&2
  exit 2
fi

mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/$NAME.shader"

if [[ -e "$OUT_FILE" ]]; then
  echo "new_urp_shader.sh: $OUT_FILE already exists; refusing to overwrite." >&2
  exit 1
fi

cat > "$OUT_FILE" <<SHADER
// $NAME — minimal URP unlit shader with one color property (_BaseColor).
// Generated by new_urp_shader.sh. URP only: the "UniversalPipeline" tag and the
// Core.hlsl include make this a URP shader; under the Built-in pipeline it will
// render magenta (no matching pass). Drive _BaseColor from C# with
// material.SetColor(Shader.PropertyToID("_BaseColor"), color).
Shader "Example/$NAME"
{
    Properties
    {
        // [MainColor] lets renderer.material.color map to this property.
        [MainColor] _BaseColor ("Base Color", Color) = (1, 1, 1, 1)
    }

    SubShader
    {
        // The RenderPipeline tag is what marks this as a URP shader.
        Tags { "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }

        Pass
        {
            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            // Material properties MUST live in a UnityPerMaterial CBUFFER for
            // this shader to be SRP Batcher compatible (URP's fast path).
            CBUFFER_START(UnityPerMaterial)
                half4 _BaseColor;
            CBUFFER_END

            struct Attributes
            {
                float4 positionOS : POSITION;
            };

            struct Varyings
            {
                float4 positionHCS : SV_POSITION;
            };

            Varyings vert(Attributes IN)
            {
                Varyings OUT;
                OUT.positionHCS = TransformObjectToHClip(IN.positionOS.xyz);
                return OUT;
            }

            half4 frag() : SV_Target
            {
                return _BaseColor;
            }
            ENDHLSL
        }
    }
}
SHADER

echo "wrote $OUT_FILE"
